improve ci/cd
Add gh action workflow to sync with halo app store

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,6 +5,8 @@ on:
     branches:
       - main
       - dev/*
+    tags:
+      - v[0-9]+.[0-9]+.[0-9]+
   pull_request:
     branches:
       - main
@@ -12,18 +14,71 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    outputs:
+      jarFileName: ${{ steps.jar.outputs.jarFileName }}
+    env:
+      # build artifact output dir
+      JAR_DIR: 'build/libs'
+
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
         with:
           fetch-depth: 0 # required by automatic version
-      - name: Setup Environment
-        uses: halo-sigs/actions/plugin-setup-env@v1
+      - name: Setup JDK
+        uses: actions/setup-java@v5
         with:
-          skip-node-setup: true
+          distribution: "temurin"
+          java-version: "21"
+          cache: "gradle"
       - name: Build with gradle
         run: ./gradlew clean build
+
+      - name: Get built jar
+        id: jar
+        run: |-
+          JARS=($JAR_DIR/*.jar)
+          JAR_NUMS=${#JARS[@]}
+          
+          if [ "$JAR_NUMS" -eq 0 ]; then
+            echo "Error: No jar files found in $JAR_DIR"
+            exit 1
+          fi
+          if [ "$JAR_NUMS" -ne 1 ]; then
+            echo "Error: Expected 1 JAR file, found $JAR_NUMS:"
+            ls "$JAR_DIR"
+            exit 1
+          fi
+          
+          JAR_FILE=${JARS[0]}
+          JAR_FILE_NAME=$(basename "$JAR_FILE")
+          echo "jarFile=$JAR_FILE" >> "$GITHUB_OUTPUT"
+          echo "jarFileName=$JAR_FILE_NAME" >> "$GITHUB_OUTPUT"
+
       - name: Upload Artifacts
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v6
         with:
-          name: artifacts
-          path: "build/libs"
+          name: ${{ steps.jar.outputs.jarFileName }}
+          path: ${{ steps.jar.outputs.jarFile }}
+          if-no-files-found: error
+
+  draft-release:
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
+    permissions:
+      contents: write
+    env:
+      JAR_FILENAME: ${{ needs.build.outputs.jarFileName }}
+
+    steps:
+      - name: Download Artifacts
+        uses: actions/download-artifact@v7
+        with:
+          name: ${{ env.JAR_FILENAME }}
+
+      - name: Draft Release
+        uses: ncipollo/release-action@v1
+        with:
+          draft: true
+          artifactErrorsFailBuild: true
+          artifacts: ${{ env.JAR_FILENAME }}
